#!/usr/bin/sh

# X keymap and setting
xsettings & 

# Notfication manager
# dunst &

# conky
# conky &

# Compositor: make shadow and transparenty
# picom  -b &
 
# get bg from bing and set to bg
nxwall &

# incerese speed of repeated key.
xset r rate 200 30 &

# clear right side of dwm statusbar
xsetroot -name " " &

# Choose monitor over laptop screen if monitor avilabe
# monitor &
