#! /usr/bin/sh

# Xorg
sudo xbps-install -y xorg-minimal xinit xauth xsetroot
# Devel
sudo xbps-install -y base-devel libX11-devel libXft-devel libXinerama-devel
# Font / sound
sudo xbps-install -y font-adobe-source-code-pro font-vazir font-inter pulseaudio 
# X
sudo xbps-install -y xclip xset setxkbmap xinput xprop xrandr 
# TOOLS
sudo xbps-install -y ffmpeg wget curl htop dmenu
# Misc
sudo xbps-install -y xdg-user-dirs xdg-utils 
# Dev
sudo xbps-install -y neovim tmux uv python git fzf zoxide 
# Apps
sudo xbps-install -y firefox pcmanfm sxiv zathura zathura-pdf-mupdf 


### Basic Sys config
sudo rm /var/service/agetty-tty{3,4,5,6}


### App Config
cd ~/.dots
cd dwm
sudo make clean install 
cd ..
cd st
sudo make clean install

# Make home directories.
cd
mkdir dl dox vids pix

mkdir dox/repos
mkdir dox/ebooks


# Link to important configs
ln -s --force ~/.dots/nvim ~/.config/nvim
ln -s --force ~/.dots/tmux ~/.config/tmux
ln -s --force ~/.dots/.xinitrc ~/.xinitrc
ln -s --force ~/.dots/.bashrc ~/.bashrc

cp ~/scripts/mimeapps.list ~/.config/mimeapps.list
cp ~/scripts/user-dirs.dirs  ~/.config/user-dirs.dirs
cp ~/scripts/.gitconfig ~/.gitconfig
cp -r ~/scripts/fontconfig/ ~/.config/fontconfig

