#! /usr/bin/sh

# Xorg
sudo xbps-install xorg-minimal xinit xauth xsetroot
# Devel
sudo xbps-install  base-devel libX11-devel libXft-devel libXinerama-devel
# Font / sound
sudo xbps-install  font-adobe-source-code-pro font-vazir font-inter pulseaudio 
# X
sudo xbps-install xclip xset setxkbmap xinput xprop xrandr 
# TOOLS
sudo xbps-install  ffmpeg wget curl htop dmenu
# Misc
sudo xbps-install  xdg-user-dirs xdg-utils 
# Dev
sudo xbps-install  neovim tmux uv python git fzf zoxide 
# Apps
sudo xbps-install  firefox pcmanfm sxiv zathura zathura-pdf-mupdf 


### Basic Sys config
sudo rm /var/service/agetty-tty{3,4,5,6}


### App Config
cd ~/.dots
cd dwm
sudo make clean install 
cd ..
cd st
sudo make clean install

# Make home directories.
cd
mkdir dl dox vids pix

mkdir dox/repos
mkdir dox/ebooks


# Link to important configs
ln -s --force ~/.dots/nvim ~/.config/nvim
ln -s --force ~/.dots/tmux ~/.config/tmux
ln -s --force ~/.dots/.xinitrc ~/.xinitrc
ln -s --force ~/.dots/.bashrc ~/.bashrc

# user-dirs
wget https://gist.githubusercontent.com/ostadsgo/f44ff05615e26917c4b2240657ebb528/raw/2e2a3a426a405666360cc13ecd8c5f78b2c48abf/user-dirs.dirs
mv user-dirs.dirs  ~/.config
xdg-user-dirs-update

# mimeapps
wget https://gist.githubusercontent.com/ostadsgo/989b352f5ac58014470c5076a9f4a5e5/raw/86a4c80554791041eebf343d71d79235a533349a/mimeapps.list
mv mimeapps.list ~/.config

# fonts config
wget https://gist.githubusercontent.com/ostadsgo/90474fd20f2c4ef4f82d9d8b58f80f2b/raw/f64576456611f4f642f0fd7f69356b95e9335fdb/fonts.conf
mkdir ~/.config/fontconfig
mv fonts.conf ~/.config/fontconfig

# gitconfig
wget https://gist.githubusercontent.com/ostadsgo/8c6f6c587a3bd3312a3bf9ad7c2f8386/raw/941abb09807fdd183598af906cd7a1b0b02633a7/.gitconfig



