#!/bin/bash


if [ $# -eq 0 ]; then
  echo "No archive file provided. Usage: $0 <archive_filename>"
  exit 1
fi


filename=$1
# Remove extention to use as dir name
basename="${filename%.*}"
if [[ "$filename" == *.zip ]]; then
  echo "Unarchive zip file"
  unzip "$filename" -d "$basename"
elif [[ "$filename" == *.tar ]]; then
  tar -xvf "$filename" -C "$basename"
  echo "Unarchive tar file"
else
  echo "Not a archive file or we don't supprot this format."
fi




