#! /usr/bin/sh

kblayout=$(setxkbmap -query | grep layout)
language=${kblayout:0-2}
title='  Keyboard Layout' 
if [ $language == "us" ] 
then
    notify-send -r 2310 "$title" 'US (English)'
    setxkbmap us
fi
if [ $language == "ir" ]
then
    notify-send -r 2310 "$title" 'IR (Persian)'
    setxkbmap ir
fi

