#!/usr/bin/sh

# rose pine
bg="#191724"
fg="#e0def4"
sel="#31748f"

# moonfly
bg="#080808"
fg="#bdbdbd"
sel="#323437"

# noclown
bg="#151515"
fg="#E1E1E1"
sel="#A2B5C1"

# darkland
bg="#080808"
fg="#cdcdcd"
sel="#708090"
dmenu_run -i -p "Apps:: " -nb $bg -nf $fg -sb $sel
